servicemesh:
  linkerd2:
    namespace: observ-example
kube-prometheus-stack:
  enabled: true
  prometheus:
    annotations:
      linkerd.io/inject: enabled
  grafana:
    podAnnotations:
      linkerd.io/inject: enabled
    ingress:
      path: /grafana/?(.*)
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
    grafana.ini:
      server:
        root_url: https://localhost:3000/grafana/
        serve_from_sub_path: true
  alertmanager:
    ingress:
      paths: [ "/alertmanager/?(.*)" ]
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/use-regex: "true"