apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: gitops-enterprise-mgmt-gke
  annotations:
    profiles.weave.works/version: v0.0.2
spec:
  description: Profile for deploying clusters chart
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: observability
      profile:
        source:
          url: git@github.com:weaveworks/profiles-catalog.git
          branch: main
          tag: observability/v0.0.1           
    - name: gitops-enterprise-mgmt-base
      dependsOn:
      - name: observability
      profile:
        source:
          url: git@github.com:weaveworks/profiles-catalog.git
          tag: gitops-enterprise-mgmt-base/v0.0.1 
    - name: security
      profile:
        source:
          url: git@github.com:weaveworks/profiles-catalog.git
          branch: main
          path: ./security-gke