{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: weaveworks-grafana-credentials
  namespace: {{ template "prometheus.namespace" . }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  admin-user: {{ index .Values "kube-prometheus-stack" "grafana" "adminUser" | b64enc | quote }}
  admin-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}