apiVersion: v2
name: observability
description: A Weaveworks Helm chart for observability
type: application
version: 0.0.1
kubeVersion: ">=1.16.0-0"
home: https://github.com/prometheus-operator/kube-prometheus
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus

keywords:
- operator
- prometheus
- kube-prometheus
- observability

annotations:
  "weave.works/profile": observability
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus

dependencies:
- name: kube-prometheus-stack
  version: "19.2.2"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: kube-prometheus-stack.enabled