apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: kyverno
spec:
  description: Profile for deploying kyverno chart
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: kyverno-crds
      chart:
        url: https://kyverno.github.io/kyverno/
        name: kyverno-crds
        version: "v2.0.3"
    - name: kyverno
      dependsOn:
      - name: kyverno-crds
      chart:
        url: https://kyverno.github.io/kyverno/
        name: kyverno
        version: "v2.0.3"
        defaultValues: |
          networkPolicy:
            enabled: true
