apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: kube-prometheus-stack
spec:
  description: Profile for deploying prometheus chart
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: kube-prometheus-stack
      chart:
        url: https://prometheus-community.github.io/helm-charts
        name: kube-prometheus-stack
        version: "18.0.12"