{{- if .Values.servicemesh.enableControlPlaneAutoRotatingCerts -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: {{ .Values.linkerd2.namespace }}
  labels:
    {{- include "linkerd2.labels" . | nindent 4 }}
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: {{ .Values.linkerd2.namespace }}
  labels:
    {{- include "linkerd2.labels" . | nindent 4 }}  
spec:
  secretName: linkerd-identity-issuer
  duration: 48h
  renewBefore: 25h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
{{ end }}