apiVersion: capi.weave.works/v1alpha1
kind: CAPITemplate
metadata:
  name: eks-with-managed-nodegroup-template
spec:
  description: This is the eks managed node group CAPA template.
  params:
    - name: CLUSTER_NAME
      description: This is used for the cluster naming.
    - name: AWS_REGION
      description: This is used for the cluster AWS region.
      options: ['us-west-1', 'us-west-2', 'us-east-1']
    - name: AWS_SSH_KEY_NAME
      description: This is used for the cluster node SSH key name.
    - name: KUBERNETES_VERSION
      description: This is used for the cluster Kubernetes version.
      options: ['v1.21', 'v1.20', 'v1.19']
    - name: WORKER_MACHINE_COUNT
      description: This is used for the cluster worker node count.
  resourcetemplates:
    - apiVersion: cluster.x-k8s.io/v1alpha4
      kind: Cluster
      metadata:
        name: "${CLUSTER_NAME}"
      spec:
        clusterNetwork:
          pods:
            cidrBlocks: ["192.168.0.0/16"]
        infrastructureRef:
          kind: AWSManagedControlPlane
          apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
          name: "${CLUSTER_NAME}-control-plane"
        controlPlaneRef:
          kind: AWSManagedControlPlane
          apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
          name: "${CLUSTER_NAME}-control-plane"
    - kind: AWSManagedControlPlane
      apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
      metadata:
        name: "${CLUSTER_NAME}-control-plane"
      spec:
        region: "${AWS_REGION}"
        sshKeyName: "${AWS_SSH_KEY_NAME}"
        version: "${KUBERNETES_VERSION}"
    - apiVersion: cluster.x-k8s.io/v1alpha4
      kind: MachinePool
      metadata:
        name: "${CLUSTER_NAME}-pool-0"
      spec:
        clusterName: "${CLUSTER_NAME}"
        replicas: ${WORKER_MACHINE_COUNT}
        template:
          spec:
            clusterName: "${CLUSTER_NAME}"
            bootstrap:
              dataSecretName: ""
            infrastructureRef:
              name: "${CLUSTER_NAME}-pool-0"
              apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
              kind: AWSManagedMachinePool
    - apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
      kind: AWSManagedMachinePool
      metadata:
        name: "${CLUSTER_NAME}-pool-0"
      spec: {}
