apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: kube-prometheus-stack-bare
spec:
  description: Profile for deploying prometheus chart
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: kube-prometheus-stack-bare
      chart:
        url: https://prometheus-community.github.io/helm-charts
        name: kube-prometheus-stack
        version: "18.0.12"
        defaultValues: |
          alertmanager:
            enabled: false
          grafana:
            enabled: false
          kubeApiServer:
            enabled: false
          kubelet:
            enabled: false
          kubeControllerManager:
            enabled: false
          coreDns:
            enabled: false
          kubeDns:
            enabled: false
          kubeEtcd:
            enabled: false         
          kubeScheduler:
            enabled: false  
          kubeStateMetrics:
            enabled: false  
          kube-state-metrics:
            enabled: false  
          nodeExporter:
            enabled: false  
          prometheus-node-exporter:
            enabled: false