apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - all.yaml
patches:
  - path: config-map-patch.yaml
  # - path: deployment-patch.yaml
  #   target:
  #     kind: Deployment
  #     name: "linkerd-identity"

patchesJson6902:
  - path: proxy-patch.json
    target:
      kind: Deployment
      name: "linkerd-proxy-injector"
  - path: proxy-patch.json
    target:
      kind: Deployment
      name: "linkerd-destination"
  - path: identity-proxy-patch.json
    target:
      kind: Deployment
      name: "linkerd-identity"
  - path: identity-vol-patch.json
    target:
      kind: Deployment
      name: "linkerd-identity"