apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: weave-gitops-enterprise-eks
  annotations:
    profiles.weave.works/version: v0.0.1
spec:
  description: Profile for deploying clusters chart
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:       
    - name: flagger
      chart:
        url: https://flagger.app
        name: flagger
        version: "1.13.0"
        defaultValues: |
          meshProvider: istio
          crd:
            create: false 
    - name: istio-base
      dependsOn:
      - name: kube-prometheus-stack
      - name: flagger    
      chart:
        path: istio/base
        defaultValues: |
          global:
            istioNamespace: default
    - name: istio-discovery
      dependsOn:
      - name: istio-base
      chart:
        path: istio/istio-discovery
        defaultValues: |
          global:
            istioNamespace: default
    - name: istio-ingress
      dependsOn:
      - name: istio-discovery
      chart:
        path: istio/istio-ingress
        defaultValues: |
          global:
            istioNamespace: default
    - name: istio-egress
      dependsOn:
      - name: istio-discovery
      chart:
        path: istio/istio-egress
        defaultValues: |
          global:
            istioNamespace: default
    - name: istio-gateway
      dependsOn:
      - name: istio-ingress
      kustomize:
        path: istio/gateway
    - name: weave-scope
      chart:
        url: https://charts.helm.sh/stable 
        name: weave-scope
        version: "1.1.12"
        defaultValues: |
          weave-scope-frontend:
            ingress:
              paths: ["/scope/?(.*)","/scope"]
              enabled: true
              annotations:
                kubernetes.io/ingress.class: mccp-nginx
                nginx.ingress.kubernetes.io/rewrite-target: /$1
                nginx.ingress.kubernetes.io/use-regex: "true"
              hosts:
                - ""
