apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: standard-cluster-deployment
spec:
  description: Profile for deploying clusters chart
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: monitoring
      profile:
        source:
          url: https://github.com/weaveworks/profiles-catalog
          tag: kube-prometheus-stack/v0.0.1
    - name: flagger
      dependsOn:
      - name: monitoring
      chart:
        url: https://flagger.app
        name: flagger
        version: "1.13.0"
        defaultValues: |
          meshProvider: istio
          metricsServer: http://kube-prometheus-stack-prometheus:9090
          crd:
            create: false 
    - name: istio
      dependsOn:
      - name: monitoring
      chart:
        url: https://storage.googleapis.com/istio-release/releases/1.1.4/charts
        name: istio
        version: "1.1.4"
        defaultValues: |
          Pilot:
            enabled: true
          Gateways:
            enabled: true
            Istio-ingressgateway:
              type: LoadBalancer
          sidecarInjectorWebhook:
            enabled: true
          Mixer:
            Policy:
              enabled: false
            Telemetry:
              enabled: true
          Prometheus:
            enabled: false