apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: standard-cluster-deployment
spec:
  description: Profile for deploying clusters chart
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: monitoring
      profile:
        source:
          url: https://github.com/weaveworks/profiles-catalog
          tag: kube-prometheus-stack/v0.0.1
    - name: flagger
      dependsOn:
      - name: monitoring
      chart:
        url: https://flagger.app
        name: flagger
        version: "1.14.0"
        defaultValues: |
          meshProvider: istio
          metricsServer: http://prometheus:9090
          crd:
            create: true 
    # - name: istio
    #   dependsOn:
    #   - name: monitoring
    #   - name: flagger
    #   kustomize:
    #     path: istio