{{- $labels := (include "external-secrets-config.labels" .) -}}
{{- range $key, $secret := .Values.secrets }}
{{- $name := keys $secret | first -}}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ $key }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- toYaml $secret | nindent 2 }}
---
{{- end -}}
