apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: weave-gitops-enterprise-eks
spec:
  description: Profile for deploying clusters chart
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: kube-prometheus-stack
      profile:
        source:
          url: git@github.com:weaveworks/profiles-catalog.git
          branch: main
          path: ./kube-prometheus-stack          
    - name: flagger
      dependsOn:
      - name: kube-prometheus-stack
      chart:
        url: https://flagger.app
        name: flagger
        version: "1.13.0"
        defaultValues: |
          meshProvider: istio
          metricsServer: http://kube-prometheus-stack-prometheus:9090
          crd:
            create: false 
    - name: istio-base
      dependsOn:
      - name: kube-prometheus-stack
      - name: flagger    
      chart:
        path: istio/base
        defaultValues: |
          global:
            istioNamespace: default
    - name: istio-discovery
      dependsOn:
      - name: istio-base
      chart:
        path: istio/istio-discovery
        defaultValues: |
          global:
            istioNamespace: default
    - name: istio-ingress
      dependsOn:
      - name: istio-discovery
      chart:
        path: istio/istio-ingress
        defaultValues: |
          global:
            istioNamespace: default
    - name: istio-egress
      dependsOn:
      - name: istio-discovery
      chart:
        path: istio/istio-egress
        defaultValues: |
          global:
            istioNamespace: default
    - name: istio-gateway
      dependsOn:
      - name: istio-ingress
      kustomize:
        path: istio/gateway
    - name: mccp-chart
      chart:
        url: https://s3.us-east-1.amazonaws.com/weaveworks-wkp/releases/charts-v3/
        name: mccp
        version: "0.0.10"
        defaultValues: |
          imagePullSecrets:
            - name: docker-io-pull-secret
          wkp-ui:
            image:
              pullSecrets:
                - docker-io-pull-secret
          dbConfig:
            databaseType: sqlite
          sqliteConfig:
            persistentVolumeClaim: true
          agentTemplate:
            natsURL: mccp-chart-nats-client:4222
          nats:
            client:
              service:
                type: LoadBalancer
          config:
            capi:
              repositoryURL: https://github.com/weaveworks/my-cluster-repo
              baseBranch: main
          nginx-ingress-controller:
            service:
              type: ClusterIP
    - name: mccp-patch
      dependsOn:
      - name: mccp-chart
      kustomize:
        path: mccp-patch
    - name: weave-scope
      profile:
        source:
          url: git@github.com:weaveworks/profiles-catalog.git
          branch: main
          path: ./weave-scope
