apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-profile-configmap
  namespace: default
data:
  mccp-chart: |
    agentTemplate:
      natsURL: mccp-chart-nats-client:4222
    config:
      capi:
        repositoryURL: https://github.com/weaveworks/my-cluster-repo
