name: Update Chart Versions

on:
  pull_request:
    branches: [ main ]

jobs:
  check-versions:
    name: Update chart versions reference in profiles
    runs-on: ubuntu-latest
    env:
      SSH_DIR: "~/.ssh"
    steps:
      - uses: actions/checkout@v2
      - name: Compare versions
        shell: bash
        env:
          GITHUB_TOKEN: ${{secrets.WEAVEWORKSBOT_PROFILES_CATALOG_RELEASE_TOKEN}}
        run: |
          for f in $(ls gitops-enterprise-mgmt-base/profile.yaml); do
              CHART_URLS=$(yq e '.spec.artifacts.[].chart.url | select(. != null)' ${PWD}/${f})
              CHART_NAMES=($(yq e '.spec.artifacts.[].chart.name | select(. != null)' ${PWD}/${f}))
              INDEX=0
              for i in ${CHART_URLS[@]}; do
                  URL=$i    
                  CHART=${CHART_NAMES[$INDEX]}
                  ((INDEX++))
                  helm repo add temp-repo $i --force-update
                  LATEST_VERSION=$(helm search repo temp-repo/$CHART -o yaml | yq e '.[0].version' -)
                  yq e -i "(.spec.artifacts[] | select(.chart.name == \"$CHART\")).chart.version = \"$LATEST_VERSION\"" ${PWD}/${f} 
              done
          done