
name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.*

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
          touch /tmp/kind-ci
          touch /tmp/gke-ci
          echo $changed | while read dir; do
            echo $dir/Chart.yaml
            if [[ $(yq e '.annotations."weave.works/profile-ci"|contains("kind")' $dir/Chart.yaml) = "true" ]]; then
              echo $dir >> /tmp/kind-ci
              echo "::set-output name=kind-ci::true"
            fi
            if [[ $(yq e '.annotations."weave.works/profile-ci"|contains("gke")' $dir/Chart.yaml) = "true" ]]; then
              echo $dir >> /tmp/gke-ci
              echo "::set-output name=gke-ci::true"
            fi
          done
          
      - name: Add dependencies
        shell: bash
        run: |
          for dir in $(ls -d charts/*/ | cut -f2 -d'/'); do
            repo_urls=$(helm dependency list charts/"$dir" | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" || true)
            i=0
            echo $repo_urls | while read urls; do
              for u in $urls; do
                if [ ! -z "$u" ] 
                then
                  echo $u
                  helm repo add $dir$i $u
                  ((i=i+1))
                fi
              done
            done
          done

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        if: steps.list-changed.outputs.kind-ci == 'true'
        uses: helm/kind-action@v1.2.0

      - name: Run chart-testing on Kind (install)
        if: steps.list-changed.outputs.kind-ci == 'true'
        run: ct install --config ct.yaml --charts $(awk '{print $1}' /tmp/kind-ci | paste -s -d, -)

      - name: Set up Cloud SDK
        if: steps.list-changed.outputs.gke-ci == 'true'
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run gke cluster
        if: steps.list-changed.outputs.gke-ci == 'true'
        shell: bash
        env:
          GKE_CLUSTER_NAME: profiles-test-mgmt-${{ github.head_ref }}-${{ github.run_number }}
          INFRASTRUCTURE: "gke"
        run: |
          make create-cluster

      - name: Run chart-testing on GKE (install)
        if: steps.list-changed.outputs.gke-ci == 'true'
        run: ct install --config ct.yaml --charts $(awk '{print $1}' /tmp/gke-ci | paste -s -d, -)

      - name: Delete gke cluster
        if: steps.list-changed.outputs.gke-ci == 'true'
        shell: bash
        env:
          GKE_CLUSTER_NAME: profiles-test-mgmt-${{ github.head_ref }}-${{ github.run_number }}
          INFRASTRUCTURE: "gke"
        run: |
          make delete-cluster