name: Makefile CI

on:
  push:
    branches: [ ci-workflow ]
  pull_request:
    branches: [ ci-workflow ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SSH_DIR: "~/.ssh"
    steps:
      - name: Setup SSH known hosts
        shell: bash
        run: |
          mkdir -p ${SSH_DIR} && chmod 700 ${SSH_DIR}
          ssh-keyscan github.com >> ${SSH_DIR}/known_hosts
      - name: Run integration tests
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          EXAMPLES_KEY: ${{ secrets.PROFILES_EXAMPLES_PRIVATE_WEAVEWORKS_PCTL_BOT_DEPLOY_KEY }}
          GIT_TOKEN: ${{secrets.GIT_TOKEN}}
          GIT_SSH_COMMAND: /tmp/ssh_command
          GIT_SSH_COMMAND_DEBUGLOG: "1"
        run: |
          mkdir -p /tmp/git-keys
          echo "${{ secrets.PROFILES_EXAMPLES_PRIVATE_WEAVEWORKS_PCTL_BOT_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-examples-private
          chmod 600 /tmp/git-keys/weaveworks-profiles-examples-private
          echo "${{ secrets.PCTL_BOT_PCTL_TEST_REPO_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-pctl-test-repo
          chmod 600 /tmp/git-keys/weaveworks-pctl-test-repo
          ls -l ${{ github.workspace }}
          cp ${{ github.workspace }}/scripts/ssh_command.sh /tmp/ssh_command
          ls -l /tmp/
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          PATH=$PATH:$(go env GOPATH)/bin make test
