name: Release Charts

on:
  push:
    branches:
      - charts-release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important parameter

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      - name: Add dependencies
        shell: bash
        run: |
          for dir in $(ls -d charts/*/ | cut -f2 -d'/'); do
            repo_urls=$(helm dependency list charts/"$dir" | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" || true)
            i=0
            echo $repo_urls | while read urls; do
              for u in $urls; do
                if [ ! -z "$u" ] 
                then
                  echo $u
                  helm repo add $dir$i $u
                  ((i=i+1))
                fi
              done
            done
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.WEAVEWORKSBOT_PROFILES_CATALOG_RELEASE_TOKEN }}"